# Generated by Django 5.1.4 on 2024-12-19 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=50)),
                ('range', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('school_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('image', models.ImageField(default='default.png', upload_to='profile/')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
