# Generated by Django 5.1.4 on 2024-12-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school_id',
            field=models.CharField(default='defalut', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
