# Generated by Django 4.2.16 on 2024-11-21 02:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9)])),
                ('range', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=30)),
                ('team', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('project_code', models.CharField(max_length=20)),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('comment', models.CharField(max_length=200)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scb.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=11)),
                ('board_comment', models.CharField(max_length=255)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scb.profile')),
            ],
        ),
    ]
